- name: varaiables at playbook level
  hosts: local
  connections: local
  vars:
   name:sateesh
   id:1320733
  tasks:
  - name: print the varaiables
    ansible.builtin.debug:
     msg: "employee name is  {{ name }}" 
     msg: "Employee id is {{ id }}"