- name: varaiables at playbook level
  hosts: local
  connection: local
  vars:
  -empdata:
    empname:sateesh
    id:1320733
  tasks:
  - name: print the varaiables
    ansible.builtin.debug:
      msg: "employee name is  {{ 'empname' }}" 
      msg: "Employee id is {{ 'id' }}"