- name: varaiables at playbook level
  hosts: local
  connection: local
  vars:
    EMPNAME: "sateesh"
    ID: 1320733
  tasks:
  - name: print the varaiables
    ansible.builtin.debug:
      msg: "employee name is  {{ EMPNAME }}" 
      msg: "Employee id is {{ ID }}"